package cmd

import (
	"errors"
	"os"
	"path/filepath"

	"github.com/callmeradical/kaleidoscope/output"
)

// exitFn is a var so tests can override it to capture exit codes.
var exitFn = os.Exit

// hookScript is the pre-commit shell script written by ks install-hook.
const hookScript = `#!/bin/sh
# kaleidoscope pre-commit hook — advisory, non-blocking
# Generated by 'ks install-hook'. Edit at your own risk.
# This hook always exits 0 so it never blocks commits.

# Ensure ks is available in PATH.
if ! command -v ks > /dev/null 2>&1; then
  printf '{"ok":false,"command":"pre-commit","error":"ks not found in PATH","hint":"Install kaleidoscope: go install github.com/callmeradical/kaleidoscope@latest"}\n'
  exit 0
fi

# Auto-start Chrome via 'ks start' if not already running.
if ! ks status > /dev/null 2>&1; then
  printf '{"ok":false,"command":"pre-commit","error":"browser not running, attempting to start"}\n'
  if ! ks start > /dev/null 2>&1; then
    printf '{"ok":false,"command":"pre-commit","error":"could not start Chrome","hint":"Run 'ks start' manually or ensure project URLs are reachable"}\n'
    exit 0
  fi
fi

# Run ks snapshot; capture output and surface it to stdout for agent consumption.
SNAPSHOT_OUT=$(ks snapshot 2>&1)
SNAPSHOT_EXIT=$?
printf '%s\n' "$SNAPSHOT_OUT"
if [ $SNAPSHOT_EXIT -ne 0 ]; then
  exit 0
fi

# Run ks diff and emit structured JSON to stdout.
DIFF_OUT=$(ks diff 2>&1)
printf '%s\n' "$DIFF_OUT"

exit 0
`

// findGitRoot walks upward from dir until it finds a .git directory,
// returning the absolute path of the repository root.
func findGitRoot(dir string) (string, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(abs, ".git")); err == nil {
			return abs, nil
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return "", errors.New("not a git repository")
		}
		abs = parent
	}
}

// RunInstallHook implements 'ks install-hook': writes a git pre-commit hook
// that runs ks snapshot && ks diff on every commit.
func RunInstallHook(args []string) {
	force := hasFlag(args, "--force")

	// Validate .ks-project.json exists in the current directory.
	if _, err := os.Stat(".ks-project.json"); os.IsNotExist(err) {
		output.Fail("install-hook", errors.New("no .ks-project.json found in current directory"), "Run `ks init` to create a project config first")
		exitFn(2)
		return
	}

	// Find the git root from the current directory.
	gitRoot, err := findGitRoot(".")
	if err != nil {
		output.Fail("install-hook", err, "Run `ks install-hook` from inside a git repository")
		exitFn(2)
		return
	}

	hookPath := filepath.Join(gitRoot, ".git", "hooks", "pre-commit")

	// Check for existing hook.
	_, statErr := os.Stat(hookPath)
	existedBefore := statErr == nil
	if existedBefore && !force {
		output.Fail("install-hook", errors.New("pre-commit hook already exists: "+hookPath), "Use --force to overwrite")
		exitFn(2)
		return
	}

	// Write the hook script with executable permissions.
	if err := os.WriteFile(hookPath, []byte(hookScript), 0755); err != nil {
		output.Fail("install-hook", err, "")
		exitFn(2)
		return
	}

	output.Success("install-hook", map[string]any{
		"hookPath":  hookPath,
		"overwrite": force && existedBefore,
	})
}
