package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/callmeradical/kaleidoscope/output"
)

// osExit is a variable so tests can replace it to avoid calling os.Exit.
var osExit = os.Exit

const hookScript = `#!/bin/sh
# kaleidoscope pre-commit hook — auto-generated by 'ks install-hook'
# Advisory only: always exits 0. Output is structured JSON for agent consumption.

set -e

# Auto-start Chrome if not running (no-op when already up)
ks start --local 2>/dev/null || true

# Capture snapshot of all project URLs
SNAPSHOT_OUT=$(ks snapshot 2>&1)
echo "$SNAPSHOT_OUT"

# Run diff against baseline; output JSON regardless of result
DIFF_OUT=$(ks diff 2>&1)
echo "$DIFF_OUT"

# Always exit 0 — advisory only, the agent decides
exit 0
`

// findGitRoot walks upward from startDir looking for a .git directory.
// Returns the directory containing .git, or an error if not found within 10 levels.
func findGitRoot(startDir string) (string, error) {
	dir := startDir
	for i := 0; i < 10; i++ {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", errors.New("not inside a git repository")
}

// RunInstallHook installs a git pre-commit hook for automatic regression checks.
func RunInstallHook(args []string) {
	force := hasFlag(args, "--force")

	// Validate .ks-project.json exists in CWD
	if _, err := os.Stat(".ks-project.json"); err != nil {
		output.Fail("install-hook", fmt.Errorf(".ks-project.json not found"), "Run 'ks init' to create a project config before installing the hook.")
		osExit(2)
		return
	}

	// Find git root
	cwd, err := os.Getwd()
	if err != nil {
		output.Fail("install-hook", err, "Could not determine current directory.")
		osExit(2)
		return
	}

	gitRoot, err := findGitRoot(cwd)
	if err != nil {
		output.Fail("install-hook", errors.New("not inside a git repository"), "Run this command from inside a git repository.")
		osExit(2)
		return
	}

	hookPath := filepath.Join(gitRoot, ".git", "hooks", "pre-commit")

	// Check for existing hook (warn and exit unless --force)
	if !force {
		if _, err := os.Stat(hookPath); err == nil {
			output.Fail("install-hook", fmt.Errorf("pre-commit hook already exists at %s", hookPath), "Use --force to overwrite the existing hook.")
			osExit(2)
			return
		}
	}

	// Ensure hooks directory exists
	if err := os.MkdirAll(filepath.Dir(hookPath), 0755); err != nil {
		output.Fail("install-hook", err, "Could not create hooks directory.")
		osExit(2)
		return
	}

	// Write hook script with executable permissions
	if err := os.WriteFile(hookPath, []byte(hookScript), 0755); err != nil {
		output.Fail("install-hook", err, "Could not write hook file.")
		osExit(2)
		return
	}

	output.Success("install-hook", map[string]any{
		"hook":    hookPath,
		"message": "pre-commit hook installed. Run 'ks diff' after each commit to review regressions.",
	})
}
